FROM node:22

WORKDIR /usr/src/app

# Copy only package files first
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Then copy the rest of the app
COPY . .

EXPOSE 3000

# Start the app
CMD ["npm", "run", "start:prod"]