name: Deploy Docker App

on:
  push:
    branches:
      - master  # adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Navigating to project directory..."
            cd /var/www/${{ secrets.PROJECT }}

            echo "Pulling latest changes..."
            git pull origin master

            echo "Building and restarting Docker containers..."
            docker compose down
            docker compose up -d --build

            echo "✅ Deployment complete."
